name: Auto Rebase

on:
  push:
    branches:
      - master
    tags:
      - "!*"
  schedule:
    - cron:  '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Github Info
      run: |
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "github.event_name: ${{ github.event_name }}"
        cat $GITHUB_EVENT_PATH

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '2.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install semantic_version

    - name: Rebase
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        REBASE_GITHUB_TOKEN: ${{ secrets.REBASE_GITHUB_TOKEN }}
        GIT_URL: ${{ secrets.GIT_URL }}
        GIT_UPSTREAM_URL: ${{ secrets.GIT_UPSTREAM_URL }}
      run: bash marge.sh $GITHUB_USERNAME $REBASE_GITHUB_TOKEN $GIT_URL $GIT_UPSTREAM_URL
